language: go
install:
- bash .travis-fork-fix
- go get github.com/mattn/goveralls
- go get github.com/lpabon/tm
- go get -v -d ./...
env:
  global:
  - secure: XbgkCwQcPJzpkaVR9HJPyKezpEDrZQEHwhYueiWgsC7YKJIqROfHQ/EPZNQpXCW/v24Sp4RQeQf4RMcnnj5Dy7XBzbkBmMIjZs/Tvp8wTwFk0BqrD2oFm7Uc//iAIIgrUnOgJl/d+GcmZHyVOhHiAuNwJTIP4Cnmjk8DKL7DdU8=
matrix:
  include:
  - go: 1.5.3
    env: OPTIONS="-race"
  - go: 1.6.1
    env: COVERAGE="true" OPTIONS=""
script:
- go fmt ./... | wc -l | grep 0
- go vet ./...
- go test -v $OPTIONS ./...
- if [[ -n "$COVERAGE" ]]; then bash .travis-coverage; fi
